#!/bin/bash

# Run game

python3 -m pip install --user virtualenv
python3 -m venv env
source ../../../bin/activate
python3 -m pip install --user pygame
python3 -m pip install --user more_itertools
python3 localSnarl.py
