#!/bin/bash

# Run game
python3 -m pip install --user virtualenv
python3 -m venv env
source "env/bin/activate"
pip install pygame
pip install more_itertools

echo "Dependencies installed! Now, run ./localSnarl args..."

